### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by crusaderkarthik** [Khizar29/carpool-webapp#1]
Hello Khizar, Do you have any images of this working platform. Just wanted to see how it looks before I start working on this project. I am really interested the code it was structured. If there are any images of working code, then it will be helpful

Regards,
Karthik K

**Comment by Khizar29** [comment]
Hi Karthik,

I hope you're doing well! I’ve attached some images of the project that I
have at the moment. Feel free to take a look and let me know your thoughts.

Also, please consider giving a star to the repository if you find it useful!

Best regards,
Syed Khizar Ali

**Comment by crusaderkarthik** [comment]
Sorry, Khizar 
I coudn't find any images -_-
Am I unable to see or you forgot to attach the images. Could you please check

Regards
Karthik K

**Comment by Khizar29** [comment]
please send me your personal email, i can email you the screenshot. I don't
know why you can't open the attached images.

**Comment by crusaderkarthik** [comment]
Here is my email Khizar
crusaderkarthik@gmail.com

**Comment by crusaderkarthik** [comment]
Thanks for sharing, really liked your work. Will do my best in my free time to improve this
